// ─── TUCSON WEALTH MAP — DATA.JS ─────────────────────────────────────────────
// Sources: Redfin Apr 2026, ACS 2023 5yr, Zillow ZHVI, CoStar/AZ DOR, Census TIGER

const MAPBOX_TOKEN = 'pk.eyJ1IjoiY2RjcmVzdGlucyIsImEiOiJjbW9hZnhzeXIwNmh0MnBwd3g2djN4ODR0In0.OtGVl5R5yfKnXyDkTXvq7A';

// ── FOURSQUARE CONFIG ─────────────────────────────────────────────────────────
// Get your FREE key at: https://location.foursquare.com/developer/
// Sign up → Create App → Copy API Key → paste below
// Free tier: 10,000 calls/month, no credit card needed
const FSQ_KEY = 'E0VZYDFHUYQPI5VY5BUXXUFQOARZQ1NXPEFQW50OT1MNDNO2';
const USE_FSQ = FSQ_KEY !== 'YOUR_FOURSQUARE_API_KEY_HERE';

// ── ZIP CODE DATA ─────────────────────────────────────────────────────────────
const ZIP_DATA = {
  // ── TUCSON METRO ──────────────────────────────────────────────────────────
  "85718":{ name:"Catalina Foothills",     city:"Tucson",   county:"Pima", medianHome:774450, medianIncome:112664, avgIncome:170918, perCapitaIncome:80249, population:31842, households:13190, medAge:52.4, unemployment:3.1, povertyRate:4.2,  collegeEd:74, ownerOccupied:82, renterOccupied:18, bizIndex:88, totalBusinesses:1240, retailSqFt:380000, vacancyRate:4.2, avgRent:28.50, medDaysOnMarket:38, homeAppreciation1yr:6.2, homeAppreciation5yr:54.7, pricePerSqFt:342, listPriceVsSale:98.1, tags:["Luxury Residential","HNW Households","Gated Communities","Mountain Views"], opp:"premium", sectors:["Wealth Management","Luxury Retail","Concierge Medical","Fine Dining","Real Estate"], brief:"Premier enclave with the highest HNW household concentration in the metro. Median income exceeds $112K with average household income over $170K. Very limited inventory keeps values firm at $774K median. Best for financial advisors, luxury brands, concierge medicine, and estate planning." },
  "85749":{ name:"Rincon Valley",          city:"Tucson",   county:"Pima", medianHome:795000, medianIncome:108500, avgIncome:145000, perCapitaIncome:62000, population:21840, households:7620,  medAge:42.1, unemployment:2.8, povertyRate:3.1,  collegeEd:69, ownerOccupied:88, renterOccupied:12, bizIndex:58, totalBusinesses:380,  retailSqFt:95000,  vacancyRate:7.8, avgRent:22.00, medDaysOnMarket:42, homeAppreciation1yr:8.4, homeAppreciation5yr:58.1, pricePerSqFt:318, listPriceVsSale:97.8, tags:["Highest Home Values","Mountain Estates","SE Foothills","Luxury New Build"], opp:"high",    sectors:["Premium Grocery","Fitness/Wellness","Financial Services","Quality Dining","Childcare"], brief:"Rincon Valley carries the highest median home values in the metro at $795K reflecting large custom-estate lots with Rincon Mountain views. 88% owner-occupancy and +58% 5yr appreciation. Massive retail service gap — first-mover opportunity in multiple categories." },
  "85750":{ name:"Tanque Verde / NE",      city:"Tucson",   county:"Pima", medianHome:549000, medianIncome:100146, avgIncome:152089, perCapitaIncome:75512, population:24680, households:9870,  medAge:47.2, unemployment:2.4, povertyRate:3.8,  collegeEd:70, ownerOccupied:79, renterOccupied:21, bizIndex:74, totalBusinesses:820,  retailSqFt:290000, vacancyRate:5.1, avgRent:26.00, medDaysOnMarket:35, homeAppreciation1yr:7.1, homeAppreciation5yr:54.6, pricePerSqFt:285, listPriceVsSale:98.5, tags:["Upscale NE Corridor","Aerospace Workforce","Strong Appreciation"], opp:"high",    sectors:["Premium Services","Medical Specialists","Boutique Fitness","Specialty Food"], brief:"Strong dual-income households with median income over $100K. Raytheon and tech professionals dominate. Houghton/Tanque Verde retail node significantly underserved relative to purchasing power." },
  "85737":{ name:"Oro Valley Core",        city:"Oro Valley",county:"Pima",medianHome:510000, medianIncome:88200,  avgIncome:118500, perCapitaIncome:63000, population:47820, households:20140, medAge:50.1, unemployment:2.2, povertyRate:3.4,  collegeEd:66, ownerOccupied:77, renterOccupied:23, bizIndex:81, totalBusinesses:2180, retailSqFt:1240000,vacancyRate:4.8, avgRent:24.50, medDaysOnMarket:32, homeAppreciation1yr:5.8, homeAppreciation5yr:55.8, pricePerSqFt:248, listPriceVsSale:99.1, tags:["Master Planned","Most Affluent City","Top Schools","Low Crime"], opp:"premium", sectors:["Healthcare","Financial Planning","Premium Retail","Senior Services"], brief:"Most affluent incorporated city in the Tucson metro. Oracle Corporation and Ventana Medical (Roche) anchor white-collar employment. Nationally-ranked schools, low crime. Commercial vacancy at 4.8% reflects near-full absorption." },
  "85739":{ name:"Catalina / N Oro Valley",city:"Catalina", county:"Pima", medianHome:464725, medianIncome:78400,  avgIncome:104000, perCapitaIncome:52000, population:15620, households:6840,  medAge:55.8, unemployment:2.6, povertyRate:3.9,  collegeEd:63, ownerOccupied:81, renterOccupied:19, bizIndex:62, totalBusinesses:420,  retailSqFt:148000, vacancyRate:8.4, avgRent:20.50, medDaysOnMarket:45, homeAppreciation1yr:6.9, homeAppreciation5yr:57.7, pricePerSqFt:225, listPriceVsSale:97.2, tags:["Active Retirement","Saddlebrooke Ranch","Golf Communities"], opp:"high",    sectors:["Golf/Recreation","Senior Healthcare","Wellness","Premium Dining"], brief:"Gateway to Saddlebrooke and Rancho Vistoso. Affluent active retirees with high net worth and equity. Wellness, concierge healthcare, and premium dining dramatically underserved." },
  "85742":{ name:"Marana / Thornydale NW", city:"Marana",   county:"Pima", medianHome:395000, medianIncome:82500,  avgIncome:104000, perCapitaIncome:50000, population:34180, households:12640, medAge:36.2, unemployment:2.9, povertyRate:4.1,  collegeEd:54, ownerOccupied:74, renterOccupied:26, bizIndex:70, totalBusinesses:890,  retailSqFt:420000, vacancyRate:6.2, avgRent:22.00, medDaysOnMarket:28, homeAppreciation1yr:9.1, homeAppreciation5yr:51.4, pricePerSqFt:218, listPriceVsSale:99.4, tags:["#1 Growth ZIP","Young Families","New Master Plans","Commercial Lag"], opp:"emerging", sectors:["Premium Grocery","Childcare","QSR/Fast Casual","Medical Clinics","Fitness"], brief:"Marana is the fastest-growing community in the Tucson MSA. Commercial base outpaced by residential 3:1. Premium grocery, pediatric healthcare, and quality restaurants face essentially zero competition." },
  "85741":{ name:"NW Tucson / Cortaro",    city:"Tucson",   county:"Pima", medianHome:360000, medianIncome:75400,  avgIncome:95200,  perCapitaIncome:46000, population:26140, households:10820, medAge:42.8, unemployment:3.1, povertyRate:5.2,  collegeEd:52, ownerOccupied:72, renterOccupied:28, bizIndex:68, totalBusinesses:1120, retailSqFt:580000, vacancyRate:5.8, avgRent:21.50, medDaysOnMarket:30, homeAppreciation1yr:4.8, homeAppreciation5yr:46.2, pricePerSqFt:207, listPriceVsSale:98.8, tags:["Established NW Suburb","Good Schools","Stable","Consistent Demand"], opp:"stable",  sectors:["Full-Service Dining","Medical","Home Services","Boutique Retail"], brief:"Casas Adobes area — one of Tucson's most stable communities. Raytheon employees and long-tenured professionals anchor consistent demand. Best for businesses seeking stable cash flow." },
  "85716":{ name:"Sam Hughes / Colonia",   city:"Tucson",   county:"Pima", medianHome:399900, medianIncome:49061,  avgIncome:72352,  perCapitaIncome:35729, population:12480, households:5920,  medAge:39.4, unemployment:3.4, povertyRate:11.2, collegeEd:72, ownerOccupied:52, renterOccupied:48, bizIndex:68, totalBusinesses:680,  retailSqFt:120000, vacancyRate:3.8, avgRent:24.00, medDaysOnMarket:22, homeAppreciation1yr:5.4, homeAppreciation5yr:48.3, pricePerSqFt:295, listPriceVsSale:101.2,tags:["Historic District","UA Adjacent","Most Walkable","Competitive Market"], opp:"high",    sectors:["Boutique F&B","Specialty Retail","Wine/Spirits","Fitness"], brief:"Tucson's most walkable historic neighborhood. Real estate sells above list price (101.2% ratio) — rarest phenomenon in local market. Coffee shops, wine bars, and boutiques outperform here." },
  "85704":{ name:"Oracle / Ina Corridor",  city:"Tucson",   county:"Pima", medianHome:335000, medianIncome:76915,  avgIncome:106358, perCapitaIncome:50631, population:28640, households:11840, medAge:44.1, unemployment:3.3, povertyRate:5.8,  collegeEd:48, ownerOccupied:69, renterOccupied:31, bizIndex:76, totalBusinesses:2240, retailSqFt:1480000,vacancyRate:5.4, avgRent:22.00, medDaysOnMarket:33, homeAppreciation1yr:3.9, homeAppreciation5yr:42.1, pricePerSqFt:196, listPriceVsSale:98.4, tags:["Primary Retail Corridor","High Traffic Counts","NW Anchor","Big Box"], opp:"stable",  sectors:["Auto Services","QSR","Medical Offices","Fitness","Insurance"], brief:"NW Tucson's dominant retail spine — highest retail square footage of any Tucson ZIP. Traffic counts exceed 40,000 vehicles/day at Oracle/Ina. Foothills Mall anchors. Captive audience from 85741/85742/85737." },
  "85745":{ name:"Tucson Mountains / W",   city:"Tucson",   county:"Pima", medianHome:425000, medianIncome:71348,  avgIncome:98301,  perCapitaIncome:45000, population:32640, households:13180, medAge:41.2, unemployment:4.8, povertyRate:8.4,  collegeEd:42, ownerOccupied:65, renterOccupied:35, bizIndex:45, totalBusinesses:640,  retailSqFt:180000, vacancyRate:10.2,avgRent:17.50, medDaysOnMarket:41, homeAppreciation1yr:7.3, homeAppreciation5yr:52.1, pricePerSqFt:235, listPriceVsSale:97.4, tags:["Hidden Wealth","Desert Estates","Undercommercialized","Strong Appreciation"], opp:"value",   sectors:["Specialty Food","Outdoor Recreation","Home Services","Healthcare"], brief:"Surprisingly high median home values ($425K) reflecting Tucson Mountain Park adjacency. Average income of $98K. The gap between income/home wealth and available commercial services is striking — dramatically undercommercialized." },
  "85715":{ name:"Broadway Village / E",   city:"Tucson",   county:"Pima", medianHome:396500, medianIncome:82651,  avgIncome:114064, perCapitaIncome:53359, population:24820, households:10840, medAge:42.6, unemployment:3.7, povertyRate:5.9,  collegeEd:43, ownerOccupied:68, renterOccupied:32, bizIndex:64, totalBusinesses:980,  retailSqFt:480000, vacancyRate:8.1, avgRent:19.50, medDaysOnMarket:31, homeAppreciation1yr:5.2, homeAppreciation5yr:44.8, pricePerSqFt:215, listPriceVsSale:98.6, tags:["Higher Income Than Appears","Aging Strip Centers","Reno Opportunity"], opp:"value",   sectors:["Restaurant Row","Medical/Dental","Value Retail","Fitness"], brief:"Median income of $82K and average of $114K make this one of Tucson's most underrated ZIPs. Strong purchasing power in aging 1970s-80s strip centers. Value-add commercial opportunity is major." },
  "85747":{ name:"Rita Ranch / SE Growth", city:"Tucson",   county:"Pima", medianHome:395000, medianIncome:78500,  avgIncome:96000,  perCapitaIncome:43000, population:19840, households:7180,  medAge:37.4, unemployment:3.2, povertyRate:4.8,  collegeEd:49, ownerOccupied:79, renterOccupied:21, bizIndex:60, totalBusinesses:420,  retailSqFt:180000, vacancyRate:6.8, avgRent:20.50, medDaysOnMarket:27, homeAppreciation1yr:8.8, homeAppreciation5yr:56.2, pricePerSqFt:214, listPriceVsSale:99.8, tags:["Raytheon Workforce","Military Families","Top Appreciation","Service Gap"], opp:"emerging", sectors:["Family Dining","Childcare","Medical","Premium Grocery","Fitness"], brief:"Rita Ranch is being built out rapidly by Raytheon missile employees and Davis-Monthan families. Homes selling at 99.8% of list. +56% 5yr appreciation leads most of Tucson. Commercial options remain very limited." },
  "85711":{ name:"Midtown / Country Club",  city:"Tucson",  county:"Pima", medianHome:335000, medianIncome:56121,  avgIncome:71607,  perCapitaIncome:38000, population:34840, households:16280, medAge:38.8, unemployment:4.1, povertyRate:12.8, collegeEd:46, ownerOccupied:51, renterOccupied:49, bizIndex:72, totalBusinesses:1680, retailSqFt:680000, vacancyRate:9.4, avgRent:18.50, medDaysOnMarket:29, homeAppreciation1yr:4.4, homeAppreciation5yr:41.2, pricePerSqFt:198, listPriceVsSale:98.2, tags:["Medical Corridor","Gentrification Signal","Speedway Strip"], opp:"value",   sectors:["Medical/Clinical","F&B","Mixed-Use","Fitness"], brief:"Speedway corridor through 85711 contains significant commercial infrastructure serving the medical cluster around TMC and Carondelet. Gentrification visible in pockets near Sam Hughes." },
  "85712":{ name:"Midtown East / Craycroft",city:"Tucson",  county:"Pima", medianHome:269450, medianIncome:48185,  avgIncome:69336,  perCapitaIncome:34000, population:30640, households:14820, medAge:38.2, unemployment:4.8, povertyRate:15.2, collegeEd:42, ownerOccupied:49, renterOccupied:51, bizIndex:65, totalBusinesses:1240, retailSqFt:520000, vacancyRate:10.8,avgRent:17.00, medDaysOnMarket:34, homeAppreciation1yr:3.2, homeAppreciation5yr:38.4, pricePerSqFt:178, listPriceVsSale:97.8, tags:["Renter-Majority","Steady Mid-Market","Broadway Corridor"], opp:"stable",  sectors:["Convenience Retail","Auto Services","QSR","Medical"], brief:"Steady mid-market zone with consistent service demand. Majority-renter population creates reliable demand for non-discretionary categories. Aging commercial inventory creates low-cost entry." },
  "85710":{ name:"East Tucson / Pantano",  city:"Tucson",   county:"Pima", medianHome:310000, medianIncome:58200,  avgIncome:74000,  perCapitaIncome:36000, population:37240, households:15680, medAge:36.8, unemployment:4.6, povertyRate:11.4, collegeEd:38, ownerOccupied:56, renterOccupied:44, bizIndex:60, totalBusinesses:980,  retailSqFt:440000, vacancyRate:9.8, avgRent:17.50, medDaysOnMarket:36, homeAppreciation1yr:3.8, homeAppreciation5yr:40.6, pricePerSqFt:189, listPriceVsSale:97.6, tags:["Working Families","DMAFB Corridor","Affordable Entry"], opp:"stable",  sectors:["Auto","QSR","Grocery","Healthcare","Value Retail"], brief:"Large working-family population with stable demand driven by military households and local employment. Home values appreciated meaningfully (+41% over 5yrs). Underserved in quality dining." },
  "85748":{ name:"Pantano / SE Tucson",    city:"Tucson",   county:"Pima", medianHome:362000, medianIncome:72000,  avgIncome:91000,  perCapitaIncome:41000, population:18640, households:7280,  medAge:38.4, unemployment:3.4, povertyRate:5.8,  collegeEd:46, ownerOccupied:72, renterOccupied:28, bizIndex:54, totalBusinesses:320,  retailSqFt:120000, vacancyRate:7.2, avgRent:19.00, medDaysOnMarket:32, homeAppreciation1yr:6.1, homeAppreciation5yr:50.2, pricePerSqFt:205, listPriceVsSale:98.9, tags:["Quiet Suburban","Strong Equity","Growth Corridor","Underretailed"], opp:"emerging", sectors:["Neighborhood Retail","Medical","Family Services","Dining"], brief:"Quiet high-equity zone east of Pantano Wash. Solid median income of $72K and +50% 5yr appreciation. Very limited commercial infrastructure — residents commute for most services." },
  "85730":{ name:"SE Tucson / DM Area",    city:"Tucson",   county:"Pima", medianHome:315000, medianIncome:54800,  avgIncome:68000,  perCapitaIncome:35000, population:28640, households:11840, medAge:35.6, unemployment:4.4, povertyRate:10.8, collegeEd:36, ownerOccupied:57, renterOccupied:43, bizIndex:55, totalBusinesses:740,  retailSqFt:320000, vacancyRate:9.2, avgRent:16.50, medDaysOnMarket:38, homeAppreciation1yr:4.1, homeAppreciation5yr:41.8, pricePerSqFt:188, listPriceVsSale:97.4, tags:["DMAFB Primary Zone","Military Housing","Stable BAH Rents"], opp:"stable",  sectors:["Auto","Military Retail","QSR","Healthcare","Convenience"], brief:"Davis-Monthan AFB is the dominant economic force. Military BAH rates stabilize rental demand counter-cyclically. E-commerce-resistant businesses perform reliably. Long-term recession-resistant thesis." },
  "85719":{ name:"University / 4th Avenue",city:"Tucson",   county:"Pima", medianHome:384900, medianIncome:41086,  avgIncome:62760,  perCapitaIncome:24663, population:20480, households:8640,  medAge:27.8, unemployment:7.2, povertyRate:28.4, collegeEd:62, ownerOccupied:28, renterOccupied:72, bizIndex:80, totalBusinesses:1680, retailSqFt:480000, vacancyRate:6.8, avgRent:28.00, medDaysOnMarket:24, homeAppreciation1yr:4.2, homeAppreciation5yr:39.8, pricePerSqFt:292, listPriceVsSale:99.1, tags:["UA Economy","#1 Foot Traffic","F&B Dominant","Seasonal"], opp:"special",  sectors:["F&B","Nightlife","Co-Working","Student Housing","Specialty Retail"], brief:"UA generates $2.2B in annual economic impact concentrated here. Commercial revenue per sq ft is the highest in Tucson despite low residential incomes — this is a volume game. Peak revenue Sep–Apr." },
  "85701":{ name:"Downtown Tucson",        city:"Tucson",   county:"Pima", medianHome:305000, medianIncome:51794,  avgIncome:81628,  perCapitaIncome:38000, population:15240, households:7420,  medAge:31.8, unemployment:6.1, povertyRate:22.1, collegeEd:54, ownerOccupied:24, renterOccupied:76, bizIndex:84, totalBusinesses:1840, retailSqFt:620000, vacancyRate:7.4, avgRent:24.00, medDaysOnMarket:28, homeAppreciation1yr:5.8, homeAppreciation5yr:42.1, pricePerSqFt:248, listPriceVsSale:98.8, tags:["Hotel Boom","Convention Center","Arts District","Revitalizing"], opp:"high",    sectors:["Hotel/Hospitality","F&B","Co-Working","Arts","Short-Term Rental"], brief:"Downtown Tucson has seen $500M+ in investment since 2018. Congress Street has become a genuine dining and arts destination. Highest business revenue outside major retail corridors. Best market for hospitality and co-working." },
  "85705":{ name:"Barrio / 4th Ave North", city:"Tucson",   county:"Pima", medianHome:305000, medianIncome:36606,  avgIncome:50199,  perCapitaIncome:23965, population:18240, households:8140,  medAge:33.4, unemployment:6.4, povertyRate:24.8, collegeEd:44, ownerOccupied:38, renterOccupied:62, bizIndex:52, totalBusinesses:620,  retailSqFt:180000, vacancyRate:12.4,avgRent:16.50, medDaysOnMarket:31, homeAppreciation1yr:6.4, homeAppreciation5yr:44.2, pricePerSqFt:228, listPriceVsSale:98.6, tags:["Gentrifying","Early Stage","Artist Community","3-5yr Window"], opp:"emerging", sectors:["Independent F&B","Art Studios","Micro-Retail","Craft Beverage"], brief:"Most active gentrification frontier in Tucson. Below-market commercial rents at $16.50/sqft. The 3-5 year window before rents normalize is open. First-mover commercial advantage is real and time-limited." },
  "85713":{ name:"South Midtown / Kino",   city:"Tucson",   county:"Pima", medianHome:260000, medianIncome:53152,  avgIncome:68192,  perCapitaIncome:28000, population:32480, households:14620, medAge:33.8, unemployment:6.4, povertyRate:18.2, collegeEd:24, ownerOccupied:46, renterOccupied:54, bizIndex:48, totalBusinesses:880,  retailSqFt:340000, vacancyRate:13.2,avgRent:15.50, medDaysOnMarket:44, homeAppreciation1yr:3.1, homeAppreciation5yr:36.4, pricePerSqFt:162, listPriceVsSale:97.1, tags:["Medical Anchor","Transitional","Redevelopment Zone"], opp:"emerging", sectors:["Healthcare","Essential Retail","Community Banking","QSR"], brief:"TMC Healthcare and Kino Sports Complex provide 3,500+ employment anchors. City of Tucson's Kino Area Master Plan designates for major mixed-use redevelopment. Early commercial positioning ahead of public investment is viable." },
  "85308":{ name:"Flowing Wells / Rillito", city:"Tucson",  county:"Pima", medianHome:290000, medianIncome:55800,  avgIncome:72000,  perCapitaIncome:32000, population:33480, households:13640, medAge:37.8, unemployment:5.1, povertyRate:13.4, collegeEd:32, ownerOccupied:55, renterOccupied:45, bizIndex:54, totalBusinesses:960,  retailSqFt:380000, vacancyRate:10.8,avgRent:16.00, medDaysOnMarket:38, homeAppreciation1yr:3.4, homeAppreciation5yr:38.2, pricePerSqFt:175, listPriceVsSale:97.4, tags:["NW Workforce","Service Dense","Stable","Non-Discretionary"], opp:"stable",  sectors:["Essential Services","Grocery","Auto","Healthcare","Value Retail"], brief:"Dense NW working-class community with reliable non-discretionary spending. Dollar Tree, Fry's, auto parts, and urgent care perform consistently. Income slightly above city median provides marginal discretionary capacity." },
  "85706":{ name:"South Tucson / Valencia", city:"Tucson",  county:"Pima", medianHome:215000, medianIncome:42800,  avgIncome:58000,  perCapitaIncome:22000, population:44820, households:17840, medAge:31.4, unemployment:8.4, povertyRate:24.2, collegeEd:18, ownerOccupied:44, renterOccupied:56, bizIndex:42, totalBusinesses:840,  retailSqFt:360000, vacancyRate:16.2,avgRent:13.50, medDaysOnMarket:48, homeAppreciation1yr:2.1, homeAppreciation5yr:30.2, pricePerSqFt:148, listPriceVsSale:96.8, tags:["Airport Corridor","High-Density","Essential Needs","Industrial Base"], opp:"impact",  sectors:["Essential Grocery","Community Health","Dollar/Value","Logistics"], brief:"High population density with significant unmet needs. Tucson International Airport and adjacent industrial create employment anchors. Dollar General, urgent care, and financial services are proven models here." },
  "85714":{ name:"Drexel / Midvale SW",    city:"Tucson",   county:"Pima", medianHome:240000, medianIncome:55000,  avgIncome:67188,  perCapitaIncome:28000, population:36840, households:14180, medAge:32.8, unemployment:6.8, povertyRate:17.4, collegeEd:20, ownerOccupied:52, renterOccupied:48, bizIndex:40, totalBusinesses:620,  retailSqFt:240000, vacancyRate:15.4,avgRent:13.00, medDaysOnMarket:52, homeAppreciation1yr:2.4, homeAppreciation5yr:32.1, pricePerSqFt:155, listPriceVsSale:96.4, tags:["Working Class","Industrial SW","Value Market","Logistics Adjacent"], opp:"niche",   sectors:["Industrial","Auto","Essential Services","Workforce Housing","Logistics"], brief:"SW corridor with high commercial vacancy (15.4%) and very low rents ($13/sqft). Viable for industrial, auto, and logistics uses. Strategic for buyers seeking I-19 and TIA airport positioning." },
  "85746":{ name:"Drexel Heights / SW",    city:"Tucson",   county:"Pima", medianHome:321400, medianIncome:68903,  avgIncome:78644,  perCapitaIncome:34000, population:47820, households:18640, medAge:33.2, unemployment:5.2, povertyRate:9.8,  collegeEd:28, ownerOccupied:64, renterOccupied:36, bizIndex:46, totalBusinesses:780,  retailSqFt:280000, vacancyRate:11.4,avgRent:15.50, medDaysOnMarket:31, homeAppreciation1yr:4.8, homeAppreciation5yr:43.1, pricePerSqFt:176, listPriceVsSale:98.2, tags:["SW Growth Pocket","Largest Population","Younger Demographics","Underretailed"], opp:"emerging", sectors:["Family QSR","Grocery","Medical","Childcare","Discount Retail"], brief:"One of the most populous yet most commercially underserved ZIPs in Tucson. Median income of $69K is solid. Large young-family population creates consistent demand for childcare, family dining, and value-oriented grocery." },
  "85756":{ name:"South Tucson Annex",     city:"Tucson",   county:"Pima", medianHome:155100, medianIncome:62699,  avgIncome:78000,  perCapitaIncome:26000, population:37840, households:13820, medAge:30.8, unemployment:6.2, povertyRate:16.4, collegeEd:18, ownerOccupied:58, renterOccupied:42, bizIndex:36, totalBusinesses:480,  retailSqFt:180000, vacancyRate:18.4,avgRent:11.50, medDaysOnMarket:54, homeAppreciation1yr:-3.8,homeAppreciation5yr:24.1, pricePerSqFt:128, listPriceVsSale:96.2, tags:["Lowest Home Values","Industrial South","Logistics Potential"], opp:"niche",   sectors:["Industrial","Logistics","Essential Retail","Auto Salvage"], brief:"Most challenged residential market in the metro with declining YoY values. However median income of $62K shows a working community. Heavy industrial zoning and airport proximity viable for logistics and light industrial." },

  // ── MARANA ───────────────────────────────────────────────────────────────
  "85653":{ name:"Marana / Avra Valley",   city:"Marana",   county:"Pima", medianHome:342000, medianIncome:71200,  avgIncome:88000,  perCapitaIncome:38000, population:28400, households:10200, medAge:37.1, unemployment:3.4, povertyRate:6.2,  collegeEd:42, ownerOccupied:70, renterOccupied:30, bizIndex:52, totalBusinesses:680,  retailSqFt:240000, vacancyRate:8.2, avgRent:18.00, medDaysOnMarket:34, homeAppreciation1yr:7.2, homeAppreciation5yr:48.6, pricePerSqFt:192, listPriceVsSale:98.4, tags:["Marana Core","Growing Workforce","I-10 Corridor","Industrial Adjacent"], opp:"emerging", sectors:["Auto Services","QSR","Industrial Supply","Convenience","Grocery"], brief:"Marana's original core along I-10. Mix of industrial, logistics, and residential. Steady growth driven by proximity to Amazon distribution and manufacturing base. Service demand tracking population growth." },
  "85658":{ name:"Marana / Tangerine Rd",  city:"Marana",   county:"Pima", medianHome:418000, medianIncome:86400,  avgIncome:112000, perCapitaIncome:54000, population:19800, households:7200,  medAge:39.2, unemployment:2.8, povertyRate:4.4,  collegeEd:56, ownerOccupied:76, renterOccupied:24, bizIndex:61, totalBusinesses:420,  retailSqFt:180000, vacancyRate:7.4, avgRent:21.00, medDaysOnMarket:30, homeAppreciation1yr:8.6, homeAppreciation5yr:52.3, pricePerSqFt:228, listPriceVsSale:98.9, tags:["North Marana","Master Planned","Higher Income","Growth Corridor"], opp:"emerging", sectors:["Premium Grocery","Medical","Fitness","Quality Dining","Childcare"], brief:"Northern Marana's premium residential expansion. Higher income demographics with limited commercial options. Strong appreciation and above-average income make this a prime retail opportunity zone along Tangerine Road corridor." },

  // ── SAHUARITA ─────────────────────────────────────────────────────────────
  "85629":{ name:"Sahuarita / Green Valley N",city:"Sahuarita",county:"Pima",medianHome:338000,medianIncome:72400, avgIncome:91000,  perCapitaIncome:41000, population:42600, households:15800, medAge:44.2, unemployment:3.6, povertyRate:5.8,  collegeEd:46, ownerOccupied:72, renterOccupied:28, bizIndex:58, totalBusinesses:720,  retailSqFt:310000, vacancyRate:7.8, avgRent:19.00, medDaysOnMarket:32, homeAppreciation1yr:7.8, homeAppreciation5yr:49.4, pricePerSqFt:198, listPriceVsSale:98.6, tags:["Sahuarita Growth","Freeport-McMoRan Workforce","South Metro","Family Community"], opp:"emerging", sectors:["Grocery","Family Dining","Medical","Childcare","Auto Services"], brief:"Sahuarita is one of the fastest-growing communities in southern Arizona. Freeport-McMoRan Morenci operations and Raytheon supply chain drive stable dual-income households. Significant retail gap in premium and specialty categories. Strong appreciation trajectory." },

  // ── GREEN VALLEY ─────────────────────────────────────────────────────────
  "85614":{ name:"Green Valley South",     city:"Green Valley",county:"Pima",medianHome:285000,medianIncome:58400,  avgIncome:74000,  perCapitaIncome:46000, population:22800, households:11400, medAge:64.8, unemployment:2.1, povertyRate:6.4,  collegeEd:52, ownerOccupied:78, renterOccupied:22, bizIndex:56, totalBusinesses:580,  retailSqFt:280000, vacancyRate:9.2, avgRent:16.50, medDaysOnMarket:44, homeAppreciation1yr:4.2, homeAppreciation5yr:38.8, pricePerSqFt:182, listPriceVsSale:97.1, tags:["Active Adult","Retirement Community","High Equity","Stable Income"], opp:"stable",  sectors:["Healthcare","Senior Services","Grocery","Restaurants","Golf/Recreation"], brief:"Green Valley is one of Arizona's premier active adult communities. Very high median age (64.8) with significant equity wealth — most residents are mortgage-free. Stable non-discretionary spending on healthcare, food, and recreation. Low risk, consistent returns." },
  "85622":{ name:"Green Valley / Continental",city:"Green Valley",county:"Pima",medianHome:298000,medianIncome:61200,avgIncome:79000, perCapitaIncome:48000, population:18600, households:9200,  medAge:62.4, unemployment:2.3, povertyRate:5.8,  collegeEd:56, ownerOccupied:80, renterOccupied:20, bizIndex:54, totalBusinesses:440,  retailSqFt:220000, vacancyRate:8.6, avgRent:17.00, medDaysOnMarket:46, homeAppreciation1yr:3.8, homeAppreciation5yr:36.2, pricePerSqFt:188, listPriceVsSale:97.4, tags:["Active Retirement","Continental Ranch","High Equity","Established Community"], opp:"stable",  sectors:["Senior Healthcare","Dining","Golf","Home Services","Financial Advisory"], brief:"Continental Ranch area of Green Valley. Predominantly retired professionals with high net worth and significant home equity. Medical, financial advisory, and premium dining outperform. Very stable, recession-resistant market." }
};

const OPP_META = {
  premium:  { icon:"💎", label:"Premium Target",    color:"#f03060", desc:"Highest wealth concentration — luxury & financial services" },
  high:     { icon:"🎯", label:"Prime Target",       color:"#f07830", desc:"Strong wealth indicators with above-average ROI potential" },
  emerging: { icon:"🚀", label:"Emerging Market",    color:"#e8a020", desc:"Fast growth — early mover advantage available" },
  value:    { icon:"💡", label:"Value Play",         color:"#28d88e", desc:"Below-market entry with strong upside potential" },
  stable:   { icon:"🔒", label:"Stable Market",      color:"#00c8f0", desc:"Consistent demand, lower risk, reliable returns" },
  special:  { icon:"🎓", label:"Specialized Market", color:"#a78bfa", desc:"Unique demographic driver — category expertise needed" },
  niche:    { icon:"🔍", label:"Niche Opportunity",  color:"#6366f1", desc:"Specific categories viable — broader market limited" },
  impact:   { icon:"🌱", label:"Impact Opportunity", color:"#34d399", desc:"Community need, mission-driven investment" }
};

const MAX = { medianHome:795000, medianIncome:112664, bizIndex:88, perCapitaIncome:80249 };

function calcScore(zip, mode) {
  const d = ZIP_DATA[zip]; if (!d) return 0;
  const h = d.medianHome    / MAX.medianHome    * 100;
  const i = d.medianIncome  / MAX.medianIncome  * 100;
  const b = d.bizIndex;
  const p = d.perCapitaIncome / MAX.perCapitaIncome * 100;
  switch (mode) {
    case 'homes':    return Math.round(h);
    case 'income':   return Math.round((i + p) / 2);
    case 'business': return Math.round(b);
    case 'growth':   return Math.round(Math.min(100, Math.max(0, ((d.homeAppreciation5yr||0) / 60) * 100)));
    default: return Math.round(h * 0.28 + i * 0.26 + b * 0.24 + p * 0.22);
  }
}
